### ISSUE TITLE
'int' object is not subscriptable

### ISSUE THREAD

**Issue by GoodDay360** [benno1237/MinePI#13]
![image](https://user-images.githubusercontent.com/59399625/177166776-e5f9fe77-0de9-4e69-b066-cb548aba46c4.png)
```python
async def manage():
    image = Image.open(r"C:\Users\Administrator\Downloads\txeDB5P.png")
    image = await MinePI.render_3d_skin(skin_image=image,aa=True)
    image.show()
asyncio.run(manage())
```
## Possible Solution:
```python
async def manage():
    image = Image.open(r"C:\Users\Administrator\Downloads\txeDB5P.png")
    image.load()
    image = image.convert("RGBA")
    image = await MinePI.render_3d_skin(skin_image=image,aa=True)
    image.show())
asyncio.run(manage())
```
![txeDB5P](https://user-images.githubusercontent.com/59399625/177166580-b262a3d1-8ffe-448c-b478-c7692dc5fbe1.png)

**Comment by benno1237** [comment]
That's a known issue with non RGBA images. I am not sure yet whether i will fix that in the next release or just add a warning in the docs. Thanks for bringing it up again tho.

**Comment by benno1237** [comment]
Going to close this as it was fixed in the latest release. Please refer to the docs (https://minepi.readthedocs.io/en/latest/) before updating. The library structure changed quite a lot.
