### ISSUE TITLE
minePI isn't recognized by my python code

### ISSUE THREAD

**Issue by gemsb** [benno1237/MinePI#14]
![image](https://user-images.githubusercontent.com/85642836/179638131-22c233ea-417b-4557-a859-293513649c5f.png)
I downloaded everything how it should be (i think), the main branch works but as the slim skin bug, and the developer branch isn't recognized

**Comment by benno1237** [comment]
The development branch has a lot of breaking changes. Refer to the examples please. "MinePI" got renamed to minepi to make it more pythonic.
Docs are available but not guaranteed to be correct.
https://minepi.readthedocs.io/en/develop/example_usage.html
