### ISSUE TITLE
Can't render "Classic" Skins

### ISSUE THREAD

**Issue by Metriximor** [benno1237/MinePI#2]
Hi, I was trying to render a classical skin, however I got this error:

`Traceback (most recent call last):
  File "main.py", line 9, in <module>
    asyncio.run(main())
  File "Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "main.py", line 6, in main
    im = await MinePI.render_3d_skin("50e1ba76234c4496ad0f2b72a8701d6c")
  File "Python\Python39\lib\site-packages\MinePI\functions.py", line 23, in render_3d_skin
    im = await Render(user, vr, hr, hrh, vrll, vrrl, vrla, vrra, ratio, False, display_hair, display_second_layer, aa).get_render(skin_image)
  File "Python\Python39\lib\site-packages\MinePI\skin_render.py", line 110, in get_render
    self.generate_polygons(hd_ratio, skin)
  File "Python\Python39\lib\site-packages\MinePI\skin_render.py", line 552, in generate_polygons
    color = skin.getpixel(((40 * hd_ratio - 1) - i, 20 * hd_ratio + j + 16))
  File "Python\Python39\lib\site-packages\PIL\Image.py", line 1369, in getpixel
    return self.im.getpixel(xy)
IndexError: image index out of range`

This error only happens with skins that use the "classic" model, "slim" skins work just fine.
Example classic skin that crashes the library: Metriximor
Example slim skin that works as expected: Vend3tta

I wonder if this is a limitation of the library? And if there's any way to make it also able to render Classic skins? Thank you

![image](https://user-images.githubusercontent.com/27985462/121786969-1e250e80-cbbb-11eb-8ba5-b775a7635d05.png)

**Comment by benno1237** [comment]
Your skin has an old style which i thought doesnt exist anymore/gets automatically converted by the MojangAPI. At least i never saw one like that. The error is quite obvious because the body parts in your raw image are not where they are supposed to be. Here a comparison:

![test](https://user-images.githubusercontent.com/35632314/121787883-19ffed80-cbc9-11eb-9123-8dea7a0d9490.png)
![test2](https://user-images.githubusercontent.com/35632314/121787886-1cfade00-cbc9-11eb-99d1-4ba6ef9e4a69.png)

Fixing that shouldnt be too hard tho. i only have to copy the parts over. Thanks for letting me know!

**Comment by benno1237** [comment]
Not as quick as i thought. will let you know once it is fixed

**Comment by Metriximor** [comment]
Awesome, and yeah, Mojang still supports them afaik. Let me know if you need help with anything :D

**Comment by Metriximor** [comment]
If you refer to the [mojang api ](https://wiki.vg/Mojang_API#Change_Skin) you can actually see they have the "variant" field in the response, slim ones are the currently supported ones and "classic" ones are the ones like mine

**Comment by benno1237** [comment]
Thats the point. There are two different kinds of classic skins. Both of the skins i linked above are actually classics. After 1.7 I think Mojang switched from the 32x64px style raw skin image to a 64x64px one because they needed the extra space for the overlays. Slim skins didnt exist back then so they are not affected. But apparently some classic skins still use the old format. I tested like 50 accounts and none of them had it. I am very sorry for that

**Comment by Metriximor** [comment]
Oh I see, damn that's a hard bug to track down. Gg my dude

**Comment by benno1237** [comment]
Sorry for the slight delay. I just pushed an experimental fix to the (newly created) develop branch. If you want to test it, you can install it using `pip install git+https://github.com/benno1237/MinePI.git@develop#egg=MinePI --force-reinstall`

Short clarification in case you are interested. Till 1.7, Minecraft skins always had the same left and right leg/arm. Afterwards, they allowed the users to customize both individually tho. Thus they needed more room in the image and made it bigger. I resized the image of those old skins now, copied all parts over to their second location and changed the order to have them display correctly.

I will do some testing and PR it to the main branch. If you encounter any issues, let me now pls!

**Comment by Metriximor** [comment]
Thank you, I have a wide variety of minecraft accounts that I will need to generate renders for, I'll let you know if I find any issue. Nice work and thanks for the clarification :D

**Comment by benno1237** [comment]
In case you didnt reinstall yet: using --upgrade instead of --force-reinstall would probably be better.
Thanks again for having a look and testing the library

**Comment by Metriximor** [comment]
Ok so today I was trying further and checking out the overall model and I think I found some issues:
As you can see the hands are on the shoulders, and the bottom of the feet doesn't seem to be correct either.

![image](https://user-images.githubusercontent.com/27985462/121951038-514dd600-cd52-11eb-8efc-8a75009217d3.png)

For comparison, this is what it should look like:
![image](https://user-images.githubusercontent.com/27985462/121951107-66c30000-cd52-11eb-8049-ec6ee98e4dfb.png)

![image](https://user-images.githubusercontent.com/27985462/121951203-86f2bf00-cd52-11eb-97e6-b40aa2090e13.png)

**Comment by benno1237** [comment]
Thanks for letting me know. Just pushed another version to the develop branch. Should be fixed. If you encounter any other issues, let me know please.

**Comment by Metriximor** [comment]
By the way just wanna let you know it worked perfectly, kinda busy right now with irl stuff but in a few days/weeks I'll post an update on how this library is being used on our server wiki!

Thank you so much for this library it's a life saver.

**Comment by benno1237** [comment]
Looking forward to it! I will close this issue now. If you encounter any other bugs or want to suggest something, feel free to open a new issue or contact me on discord (Benno#8969)
