### ISSUE TITLE
Skin renders with some parts of arms missing.

### ISSUE THREAD

**Issue by MinekPo1** [benno1237/MinePI#6]
Render arguments:
```python
render = await MinePI.render_3d_skin(skin_image=skin,
	ratio=15,
	hr=180,
	aa=True,
)
```

Render:

![image](https://user-images.githubusercontent.com/68391527/135162275-0018f1f3-0b79-4957-8294-e7434d4f3c91.png)

Render in launcher:

![image](https://user-images.githubusercontent.com/68391527/135162611-97773b05-568d-446a-a265-c80ce23418f7.png)

Skin:

![skin](https://user-images.githubusercontent.com/68391527/135162650-7e44b82e-3cbd-49f3-86ec-7b03fa97f389.png)

Excuse my minimal word use, but I am slightly tired at the moment.

**Comment by benno1237** [comment]
Sorry for my late answer. I thought I would rather try and fix the actual issue.
Just pushed a new release to my development branch with hopefully all the required things in place. I didnt find much time to test it so any feedback is highly appreciated.
To install from my development branch use the following command:
`pip install git+https://github.com/benno1237/MinePI.git@develop#egg=MinePI --force-reinstall --no-cache-dir`
The usage didnt change compared to the previous release. My detection system for slim skins is rather bad so let me know if anything should break please.
Thanks for using the lib, cheers!

**Comment by benno1237** [comment]
Just updated once again to fix the arms. Consider updating.

**Comment by benno1237** [comment]
Going to close this as it was fixed in the latest release. Please refer to the docs (https://minepi.readthedocs.io/en/latest/) before updating. The library structure changed quite a lot.
