### ISSUE TITLE
Can you check player skin is steve type or alex type and render

### ISSUE THREAD

**Issue by SapoKR** [benno1237/MinePI#8]

**Comment by benno1237** [comment]
This should already be present? I did however slightly alter the check in the latest dev version. Its scheduled to release soon-ish alongside with cape detection.
If slim/normal detection shouldnt work for you, please let me know which exact version you are using and also provide the username/uuid/skin of the player related.
Regards

**Comment by wyndolinn** [comment]
Same problem, also translucent pixels are displayed as transparent and background is visible though them
My uuid 90564ab2-34e7-466b-8d2a-1bb14e4af1dc

**Comment by benno1237** [comment]
Going to close this as it was fixed in the latest release. Please refer to the docs (https://minepi.readthedocs.io/en/latest/) before updating. The library structure changed quite a lot.
